# Generated by Django 6.0.2 on 2026-02-12 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor_hex', models.CharField(default='#64748b', help_text='Ex: #3b82f6', max_length=7)),
                ('icone', models.CharField(blank=True, default='📊', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('link', models.URLField(verbose_name='URL do Painel')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='dashboard_covers/')),
                ('admin_only', models.BooleanField(default=False, verbose_name='Apenas Admin?')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dos Dados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.categoria')),
            ],
        ),
    ]
